# Generated by Django 3.2.19 on 2024-01-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_createlisting'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='amountOfMoney',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='createlisting',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='createlisting',
            name='picture',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='createlisting',
            name='starting_bid',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
