# Generated by Django 3.2.19 on 2024-01-20 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20240115_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.ManyToManyField(to='auctions.CreateListing')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentID', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(null=True)),
                ('dateOfComment', models.DateTimeField(auto_now_add=True)),
                ('commenterID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.createlisting')),
            ],
        ),
    ]
