# Generated by Django 3.2.19 on 2024-02-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20240201_0717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createlisting',
            name='categories',
        ),
        migrations.AddField(
            model_name='categories',
            name='listingIDs',
            field=models.ManyToManyField(to='auctions.CreateListing'),
        ),
    ]
