# Generated by Django 3.2.19 on 2024-02-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20240202_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createlisting',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='createlisting',
            name='bid',
            field=models.ManyToManyField(to='auctions.Bids'),
        ),
    ]
