# Generated by Django 3.2.19 on 2024-02-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20240202_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createlisting',
            name='bid',
        ),
        migrations.AddField(
            model_name='createlisting',
            name='starting_bid',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
