# Generated by Django 3.2.19 on 2024-02-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20240202_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createlisting',
            name='endDate',
        ),
        migrations.AddField(
            model_name='createlisting',
            name='hasEnded',
            field=models.BooleanField(default=False),
        ),
    ]
