# Generated by Django 5.0.2 on 2024-03-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20240203_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='itemId',
            field=models.ManyToManyField(related_name='items', to='auctions.createlisting'),
        ),
    ]
