# Generated by Django 5.0.2 on 2024-03-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_watchlist_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='itemId',
            field=models.ManyToManyField(to='auctions.createlisting'),
        ),
    ]
