# Generated by Django 5.0.4 on 2024-12-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_watchlist_itemid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='categoryID',
            new_name='catergoryKey',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='listingIDs',
        ),
        migrations.AddField(
            model_name='createlisting',
            name='label',
            field=models.ManyToManyField(to='auctions.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.TextField(),
        ),
    ]
