# Generated by Django 5.0.4 on 2024-12-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_remove_createlisting_label_delete_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createlisting',
            old_name='label',
            new_name='labels',
        ),
    ]
