# Generated by Django 5.0.4 on 2024-12-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_label_createlisting_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='labels',
            field=models.CharField(choices=[('Food and Beverage', 'Food and Beverage'), ('ELEC', 'Electronics and Tech'), ('HOME', 'Home and Furniture'), ('FASH', 'Fashion and Accessories'), ('HEALTH', 'Health and Beauty'), ('ENT', 'Entertainment'), ('SPORTS', 'Sports and Outdoors'), ('TOYS', 'Toys and Hobbies'), ('AUTO', 'Automotive'), ('SERV', 'Services'), ('MISC', 'Miscellaneous')], default='MISC', max_length=100),
        ),
    ]
