# Generated by Django 5.0.4 on 2024-12-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_createlisting_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createlisting',
            name='labels',
            field=models.CharField(choices=[('Food and Beverage', 'Food and Beverage'), ('Electronics and Tech', 'Electronics and Tech'), ('Home and Furniture', 'Home and Furniture'), ('Fashion and Accessories', 'Fashion and Accessories'), ('Health and Beauty', 'Health and Beauty'), ('Entertainment', 'Entertainment'), ('Sports and Outdoors', 'Sports and Outdoors'), ('Toys and Hobbies', 'Toys and Hobbies'), ('Automotive', 'Automotive'), ('Services', 'Services'), ('Miscellaneous', 'Miscellaneous')], default='MISC', max_length=100),
        ),
    ]
