# Generated by Django 5.0.4 on 2024-06-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_tags_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mediaPath',
            field=models.FilePathField(null=True),
        ),
    ]
