# Generated by Django 5.0.4 on 2025-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mediaUpload',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='defaultPP.jpg', upload_to=''),
        ),
    ]
