# Generated by Django 5.0.4 on 2024-06-25 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_mediapath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postID',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
