# Generated by Django 5.0.4 on 2025-02-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_mediaupload_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mediaUpload',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
