# Generated by Django 5.0.4 on 2024-10-14 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_mediapath_post_pictureupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('followed_id', models.ManyToManyField(related_name='followedID', to=settings.AUTH_USER_MODEL)),
                ('following_id', models.ManyToManyField(related_name='followID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
