# Generated by Django 5.0.4 on 2025-02-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_mediaupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mediaUpload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
