# Generated by Django 5.0.4 on 2025-02-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_post_mediaupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mediaUpload',
        ),
    ]
