# Generated by Django 5.0.4 on 2024-10-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pictureUpload',
        ),
        migrations.RemoveField(
            model_name='post',
            name='videoUpload',
        ),
        migrations.AddField(
            model_name='post',
            name='mediaUpload',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
