# Generated by Django 5.0.4 on 2024-11-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_pictureupload_remove_post_videoupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to='ProfileMedia/'),
        ),
    ]
