# Generated by Django 5.0.4 on 2024-11-02 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_profile_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_id',
            field=models.ManyToManyField(related_name='followedID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='following_id',
            field=models.ManyToManyField(related_name='followID', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(null=True, upload_to='ProfileMedia/'),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
