# Generated by Django 5.0.4 on 2024-11-02 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_followed_id_user_following_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilePicture',
        ),
    ]
