# Generated by Django 5.0.4 on 2024-11-07 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_remove_user_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followed_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_id',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(related_name='followers', to='network.profile')),
            ],
        ),
    ]
