# Generated by Django 5.0.4 on 2024-11-08 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_user_followed_id_remove_user_following_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
