# Generated by Django 5.0.4 on 2024-11-09 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_rename_user_profile_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
