# Generated by Django 5.0.4 on 2024-11-28 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_remove_post_likes_likes_post_amountoflikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='amountOfLikes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.likes'),
        ),
    ]
