# Generated by Django 5.0.4 on 2025-05-28 06:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cellPhone', models.CharField(max_length=120, verbose_name='cellphone number')),
                ('location', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='geolocation ip address')),
                ('dateOfBirth', models.DateField(verbose_name='date of birth')),
                ('Job', models.CharField(default='unemployed', max_length=256, verbose_name='Job Title')),
                ('education', models.CharField(choices=[('highschool', 'highschool'), ('bachelors', 'bachelors'), ('masters', 'masters'), ('phd', 'phd'), ('other', 'other')], max_length=256, verbose_name='education level')),
                ('isValidated', models.BooleanField(default=False, verbose_name='cellphone validated')),
                ('isSubscribed', models.BooleanField(default=False, verbose_name='user subscription')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Hobbies_Intreasts',
            fields=[
                ('hobbiesID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('hobbies', models.CharField(choices=[('sports', 'sports'), ('reading', 'reading'), ('gaming', 'gaming'), ('music', 'music'), ('art', 'art'), ('traveling', 'traveling'), ('cooking', 'cooking'), ('photography', 'photography'), ('writing', 'writing'), ('fitness', 'fitness'), ('fashion', 'fashion'), ('technology', 'technology'), ('nature', 'nature'), ('food', 'food')], max_length=256, verbose_name='hobbies')),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('matchID', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='match ID')),
                ('matchDate', models.DateTimeField(auto_now=True, verbose_name='match date')),
                ('isMatched', models.BooleanField(default=False)),
                ('isBlocked', models.BooleanField(default=False)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person1', to=settings.AUTH_USER_MODEL)),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('fileID', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Media Key')),
                ('fileName', models.CharField(max_length=256, verbose_name='File name')),
                ('fileData', models.FileField(upload_to='media/')),
                ('fileDate', models.DateTimeField(auto_now=True, verbose_name='file upload date')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader', to=settings.AUTH_USER_MODEL, verbose_name='uploader')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('MessageID', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='message ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='time of message')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lubdub.mediafiles', verbose_name='file attached')),
                ('matchID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matched_couple', to='lubdub.match', verbose_name='match ID')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceAnalysis',
            fields=[
                ('PreferenceID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Psyche',
            fields=[
                ('psycheID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('personalityTraits', models.CharField(max_length=256, verbose_name='personality traits')),
                ('religion', models.CharField(choices=[('christianity', 'christianity'), ('islam', 'islam'), ('hinduism', 'hinduism'), ('buddhism', 'buddhism'), ('judaism', 'judaism'), ('atheism', 'atheism'), ('agnosticism', 'agnosticism'), ('other', 'other')], max_length=256, verbose_name='religion')),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sexuality',
            fields=[
                ('SexualityID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('sex', models.CharField(choices=[('female', 'female'), ('male', 'male'), ('bigender', 'bigender')], max_length=256, verbose_name='sexual orientation')),
                ('sexuality', models.CharField(choices=[('straight', 'straight'), ('bisexual', 'bisexual'), ('lesbian', 'lesbian'), ('gay', 'gay'), ('pansexual', 'pansexual'), ('asexual', 'asexual'), ('queer', 'queer'), ('other', 'other')], max_length=256, verbose_name='sexuality')),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='humanSex', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisualAnalysis',
            fields=[
                ('visualID', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='visual ID')),
                ('height', models.PositiveIntegerField(verbose_name='persons height')),
                ('weight', models.PositiveIntegerField(verbose_name='users weight')),
                ('race', models.CharField(choices=[('white', 'white'), ('black', 'black'), ('asian', 'asian'), ('hispanic', 'hispanic'), ('mixed', 'mixed'), ('other', 'other')], max_length=80, verbose_name='Race')),
                ('bodyType', models.CharField(choices=[('skinny', 'skinny'), ('fit', 'fit'), ('average', 'average'), ('chubby', 'chubby'), ('Big', 'Big')], max_length=80, verbose_name='body type')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personsAppearance', to=settings.AUTH_USER_MODEL, verbose_name='personslooks')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hobbies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lubdub.hobbies_intreasts')),
                ('files', models.ManyToManyField(to='lubdub.mediafiles')),
                ('matches', models.ManyToManyField(to='lubdub.match')),
                ('messageIDs', models.ManyToManyField(to='lubdub.messages')),
                ('personID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('preferences', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lubdub.preferenceanalysis')),
                ('psyche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lubdub.psyche')),
                ('sexuality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lubdub.sexuality')),
                ('visual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lubdub.visualanalysis')),
            ],
        ),
    ]
