# Generated by Django 5.0.4 on 2025-05-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lubdub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
