# Generated by Django 5.0.4 on 2025-05-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lubdub', '0002_alter_person_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Job',
            field=models.CharField(default='unemployed', max_length=256, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dateOfBirth',
            field=models.DateField(null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(choices=[('highschool', 'highschool'), ('bachelors', 'bachelors'), ('masters', 'masters'), ('phd', 'phd'), ('other', 'other')], max_length=256, null=True, verbose_name='education level'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isSubscribed',
            field=models.BooleanField(default=False, null=True, verbose_name='user subscription'),
        ),
        migrations.AlterField(
            model_name='person',
            name='isValidated',
            field=models.BooleanField(default=False, null=True, verbose_name='cellphone validated'),
        ),
    ]
