# Generated by Django 5.0.4 on 2025-06-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lubdub', '0003_alter_person_job_alter_person_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='isMatched',
            field=models.BooleanField(default=True),
        ),
    ]
